# Generated by Django 5.1.3 on 2025-03-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComponentName', models.CharField(max_length=255)),
                ('Device', models.CharField(max_length=255)),
                ('SolutionBasic', models.CharField(max_length=255)),
                ('SolutionWorking', models.CharField(max_length=255)),
                ('Walvelength', models.IntegerField()),
                ('Cuvete', models.IntegerField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('UpLimitConcSubstance', models.IntegerField()),
                ('CountDensities', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountDensities', models.IntegerField()),
                ('Value', models.FloatField()),
                ('Calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='calibr_calc.calculations')),
            ],
        ),
        migrations.CreateModel(
            name='OpticalDensities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.FloatField()),
                ('Solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optical_densities', to='calibr_calc.solutions')),
            ],
        ),
    ]
