# Generated by Django 5.1.7 on 2025-04-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibr_calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='UpLimitConcSubstance',
            field=models.FloatField(),
        ),
    ]
