# Generated by Django 5.1.7 on 2025-06-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibr_calc', '0002_alter_calculations_uplimitconcsubstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='Cuvete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='Device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='SolutionBasic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='SolutionWorking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='Walvelength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
