# Generated by Django 5.1.7 on 2025-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibr_calc', '0003_alter_calculations_cuvete_alter_calculations_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='IdChange',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculations',
            name='IdCreate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='DateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
