# Generated by Django 5.1.7 on 2025-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibr_calc', '0004_calculations_idchange_calculations_idcreate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='DateTimeChange',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='DateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
