# Generated by Django 5.1.7 on 2025-07-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibr_calc', '0005_calculations_datetimechange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='Method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
