# Generated by Django 5.1.7 on 2025-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibr_calc', '0006_calculations_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='NoDelete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='DateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
