# Generated by Django 5.1.7 on 2025-07-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibr_calc', '0007_calculations_nodelete_alter_calculations_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticaldensities',
            name='NoDelete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solutions',
            name='NoDelete',
            field=models.BooleanField(default=True),
        ),
    ]
