# Generated by Django 5.1.7 on 2025-07-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibr_calc', '0008_opticaldensities_nodelete_solutions_nodelete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculations',
            name='NoDelete',
        ),
        migrations.RemoveField(
            model_name='opticaldensities',
            name='NoDelete',
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='NoDelete',
        ),
        migrations.AddField(
            model_name='calculations',
            name='ChangeOwner',
            field=models.BooleanField(default=False),
        ),
    ]
