"""
Django settings for calibrations project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%s#$u(8-7ssy+7)2it%@7!k2_0_yubo7yru2c(vi1dfbv=fgi_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Настройки CORS
CORS_ORIGIN_ALLOW_ALL = DEBUG
# Разрешить запросы от React-приложения
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",        # Разрешить запросы от React-приложения
    "http://127.0.0.1:3000",        # Разрешить запросы от React-приложения
    "http://localhost:8080",        # Разрешенные домены для CORS
    "http://127.0.0.1:8080",        # Разрешенные домены для CORS
]
CORS_ALLOW_ALL_ORIGINS = True  # В production установить False и указать конкретные домены
CORS_ALLOW_CREDENTIALS = True       # Разрешить передачу куки и заголовков авторизации
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://\w+\.example\.com$",
]
# Разрешенные методы
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
# Разрешенные заголовки
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',                      # Встроенная аутентификация Django
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',                           # DRF
    'rest_framework_simplejwt',                 # JWT аутентификация
    'rest_framework_simplejwt.token_blacklist', # Для работы blacklist (выполнить python manage.py migrate)
    'calibr_calc.apps.CalibrCalcConfig',        # Calibration    
    'drf_yasg',
    'corsheaders',                              # CORS
    'func_admins.apps.FuncAdminsConfig',        # Custom Admins
    'docum_user.apps.DocumUserConfig',          # Documentations
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'calibrations.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'calibrations.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'calibrations',
        'USER': 'postgres',  # или 'django_userpostgres'
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
# в pgAdmin
# REATE USER django_user WITH PASSWORD 'secure_password';
# GRANT ALL PRIVILEGES ON DATABASE calibrations TO django_user;

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# настройки аутенфикации
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',        # Стандартный бэкенд аутентификации Django
]

# Настройки REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',        # JWT аутентификация
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        #'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',       # По умолчанию доступ только для аутентифицированных
        # 'rest_framework.permissions.AllowAny'
    ],
}

# Настройки для уведомлений
NOTIFICATIONS = {
    'USE_JSONFIELD': True,
    'SOFT_DELETE': True,
}

# Настройки JWT
from datetime import timedelta
import os
SIMPLE_JWT = {
    # === Основные настройки токенов ===
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=3),       # Время жизни access token
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),     # Время жизни access token
    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),        # Время жизни refresh token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),        # Время жизни refresh token
    'ROTATE_REFRESH_TOKENS': True,                      # Обновлять refresh token при каждом обновлении
    'BLACKLIST_AFTER_ROTATION': True,                   # Добавлять старые токены в черный список
    'UPDATE_LAST_LOGIN': True,                          # Обновлять last_login при аутентификации
    
    # === Алгоритмы и ключи ===
    'ALGORITHM': 'HS256',                               # Алгоритм шифрования
    'SIGNING_KEY': SECRET_KEY,                          # Ключ подписи (берется из SECRET_KEY)    
    'VERIFYING_KEY': None,                              # Ключ проверки (None для HS256)
    'AUDIENCE': None,                                   # Аудитория (обычно None)
    'ISSUER': None,                                     # Издатель (обычно None)
    
    # === Заголовки авторизации ===
    'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),             # Тип заголовка авторизации
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',           # Имя заголовка авторизации
    # правило аутентификации:
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    # === Поля токенов ===
    'USER_ID_FIELD': 'id',                              # Поле модели User для идентификатора
    'USER_ID_CLAIM': 'user_id',                         # Поле в токене для идентификатора    
    'TOKEN_TYPE_CLAIM': 'token_type',                   # Поле в токене для типа токена
    'JTI_CLAIM': 'jti',                                 # Поле для уникального идентификатора токена
        
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',), # Классы токенов
    
    # === Sliding tokens (устаревшие, лучше отключить) ===
    # 'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',   # Поле для времени обновления sliding token
    # 'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),     # Время жизни sliding token
    # 'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),# Время обновления sliding token
}
# for production
# 'SIGNING_KEY': os.getenv('JWT_SECRET_KEY'),       
# 'ALGORITHM': 'RS256',  # Асимметричное шифрование
# 'SIGNING_KEY': private_key,
# 'VERIFYING_KEY': public_key,

# HTTPS Security Settings (Production Only)
if not DEBUG:  # Активируем только в production
    # Куки сессии будут передаваться только через HTTPS. Защищает от перехвата сессии через MITM-атаки.
    SESSION_COOKIE_SECURE = True
    
    # CSRF-куки будут передаваться только через HTTPS. Предотвращает подделку межсайтовых запросов.
    CSRF_COOKIE_SECURE = True
    
    # Перенаправление всех HTTP-запросов на HTTPS. Требует настройки веб-сервера (Nginx/Apache) для корректной работы.
    SECURE_SSL_REDIRECT = True
    
    # Безопасные заголовки для защиты от атак
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # Настройки для HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 год         # Время, в течение которого браузер должен использовать только HTTPS.
    SECURE_HSTS_PRELOAD = True                      # Включение в список предзагрузки HSTS (требуется регистрация в hstspreload.org).
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True           # Распространяет HSTS на все поддомены.
    
    # Дополнительная защита куки
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_HTTPONLY = True
    
    # Указываем, что сайт работает только через HTTPS. Необходимо, если Django работает за обратным прокси (Nginx/Apache).
    # Позволяет корректно определять HTTPS-соединение.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False


# Настройка веб-сервера
# Nginx:
# server {
#    listen 80;
#    server_name example.com;
#    return 301 https://$server_name$request_uri;
# }
# Apache:
# RewriteEngine On
# RewriteCond %{HTTPS} off
# RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]