# Generated by Django 5.1.4 on 2025-04-25 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('func_admins', '0002_add_profiles_to_existing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('registration', 'Регистрация'), ('verification', 'Подтверждение'), ('group_change', 'Изменение группы'), ('profile_update', 'Обновление профиля'), ('notification_sent', 'Отправка уведомления'), ('notification_read', 'Прочтение уведомления'), ('user_delete', 'Удаление пользователя'), ('calculation_create', 'Создание расчета'), ('calculation_update', 'Обновление расчета'), ('calculation_delete', 'Удаление расчета'), ('password_reset', 'Сброс пароля')], max_length=50, verbose_name='Тип действия')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата действия')),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История действия',
                'verbose_name_plural': 'История действий',
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system', 'Системное'), ('user', 'Пользовательское'), ('group', 'Групповое'), ('registration', 'Регистрация')], default='user', max_length=20, verbose_name='Тип уведомления')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('group_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_notifications', to='auth.group', verbose_name='Группа получателей')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуально')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новое')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_profile', to='func_admins.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Профиль уведомления',
                'verbose_name_plural': 'Профили уведомлений',
            },
        ),
    ]
