# Generated by Django 5.1.7 on 2025-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func_admins', '0003_actionhistory_notification_notificationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
